# Generated by Django 3.2.14 on 2022-07-29 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Illustrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LightNovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('illustration', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Publishing', 'Publishing'), ('Finished', 'Finished')], max_length=50, null=True)),
                ('authors', models.ManyToManyField(blank=True, null=True, to='api.Author')),
                ('genres', models.ManyToManyField(blank=True, null=True, to='api.Genre')),
                ('illustrators', models.ManyToManyField(blank=True, null=True, to='api.Illustrator')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('illustration', models.URLField(blank=True, null=True)),
                ('publish_date', models.DateField(blank=True, null=True)),
                ('light_novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volumes', to='api.lightnovel')),
            ],
        ),
        migrations.AddField(
            model_name='lightnovel',
            name='publishers',
            field=models.ManyToManyField(blank=True, null=True, to='api.Publisher'),
        ),
        migrations.CreateModel(
            name='AlternateName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('light_novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternatenames', to='api.lightnovel')),
            ],
        ),
    ]
