# Generated by Django 3.2.14 on 2022-07-29 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lightnovel',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
